variables:
  REMINDER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:reminder
  TAGGER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:tagger
  TAGGER_EMAIL: packages@datadoghq.com
  TAGGER_NAME: ci.integrations-core

# Uncomment when/if we modify script to use Jira
#
# release-reminder:
#   image: $REMINDER_IMAGE
#   only:
#     - master
#   script:
#     - ./.gitlab/reminder/release-reminder.sh 2>&1
#   tags: [ "runner:main", "size:large" ]

test-gitlab-api:
  image: $TAGGER_IMAGE
  script:
    - "curl -v --header \"JOB-TOKEN: $CI_JOB_TOKEN\" -X GET https://gitlab.ddbuild.io/api/v4/projects/$CI_PROJECT_ID/pipelines?per_page=100"
  tags: [ "runner:main", "size:large" ]
