variables:
  REMINDER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:reminder
  TAGGER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:tagger
  TAGGER_EMAIL: packages@datadoghq.com
  TAGGER_NAME: ci.integrations-core

# Uncomment when/if we modify script to use Jira
#
# release-reminder:
#   image: $REMINDER_IMAGE
#   only:
#     - master
#   script:
#     - ./.gitlab/reminder/release-reminder.sh 2>&1
#   tags: [ "runner:main", "size:large" ]

release-auto:
  image: $TAGGER_IMAGE
  only:
    - master
  script:
    - ddev --version
    - ddev config set core .
    # Prefix every line with a timestamp
    - ./.gitlab/tagger/tag-release.sh 2>&1 | ts "[%H:%M:%S %Z]  "
  tags: [ "runner:main", "size:large" ]

release-manual:
  image: $TAGGER_IMAGE
  only:
    # Integration release tags e.g. any_check-X.Y.Z-rc.N
    - alex/test_ci_pipeline
  script:
    # Get tagger info
    - git show rethinkdb-1.0.1 | cat -A
    - git show win32_event_log-2.3.4 | cat -A
    - git show rethinkdb-1.0.1 | head -2
    - git show win32_event_log-2.3.4 | head -2
    - echo Finished
  tags: [ "runner:main", "size:large" ]

reminder-image-builder:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  only:
    changes:
      - .gitlab/reminder/**
    refs:
      - master
  script:
    - docker build --tag $REMINDER_IMAGE ./.gitlab/reminder/
    - docker images $REMINDER_IMAGE
    - docker push $REMINDER_IMAGE
  except: [ tags, schedules ]
  tags: [ "runner:docker", "size:large" ]

tagger-image-builder:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  only:
    changes:
      - .gitlab/tagger/**
      - datadog_checks_dev/**
    refs:
      - master
  script:
    - docker build --tag $TAGGER_IMAGE -f .gitlab/tagger/Dockerfile ./datadog_checks_dev/
    - docker images $TAGGER_IMAGE
    - docker push $TAGGER_IMAGE
  except: [ tags, schedules ]
  tags: [ "runner:docker", "size:large" ]
