parameters:
  sys_platform: ''
  python_version: ''

steps:
# Install the Python version with which to use globally last as
# these tasks prepend to PATH instead of appending to it. See:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '${{ parameters.python_version }}'
  displayName: 'Use Python ${{ parameters.python_version }}'

- bash: |
    set -e
    echo Compile Deps - Hello ${{ parameters.sys_platform }}
    python --version
    ls -la

    cat datadog_checks_base/datadog_checks/base/data/agent_requirements.in | grep -v pymqi > /tmp/agent_requirements_filtered.in

    pip install pip-tools==4.5.1

    PYTHON_MAJOR_VERSION="$( cut -d '.' -f 1 <<< "${{ parameters.python_version }}" )"
    OUTPUT_FILE="agent_requirements-${{ parameters.sys_platform }}-py$PYTHON_MAJOR_VERSION.txt"
    python -m piptools compile --generate-hashes --output-file $OUTPUT_FILE /tmp/agent_requirements_filtered.in

    cp $OUTPUT_FILE $BUILD_ARTIFACTSTAGINGDIRECTORY/
    ls -la $BUILD_ARTIFACTSTAGINGDIRECTORY

    python -m pip download --no-deps -r $OUTPUT_FILE

  displayName: 'Compile Deps'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: agent_requirements
