parameters:
  sys_platform: ''

steps:
- script: |
    echo Compile Deps - Hello ${{ parameters.sys_platform }}
    python --version
    python2 --version
    python3 --version
    ls -la
  displayName: 'Compile Deps'
