parameters:
  sys_platform: ''

steps:
# Install the Python version with which to use globally last as
# these tasks prepend to PATH instead of appending to it. See:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
  displayName: 'Use Python 2.7'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    echo Compile Deps - Hello ${{ parameters.sys_platform }}
    python --version
    python2 --version
    python3 --version
    ls -la
  displayName: 'Compile Deps'
