trigger: none

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - datadog_checks_base/datadog_checks/*

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1

jobs:
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_1
    display: Test_gunicorn_py2_py3_1
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_2
    display: Test_gunicorn_py2_py3_2
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_3
    display: Test_gunicorn_py2_py3_3
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_4
    display: Test_gunicorn_py2_py3_4
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_5
    display: Test_gunicorn_py2_py3_5
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_6
    display: Test_gunicorn_py2_py3_6
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_7
    display: Test_gunicorn_py2_py3_7
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_8
    display: Test_gunicorn_py2_py3_8
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_9
    display: Test_gunicorn_py2_py3_9
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py2_py3_10
    display: Test_gunicorn_py2_py3_10
    check: 'gunicorn'
    test: true
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_1
    display: Test_gunicorn_py3_1
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_2
    display: Test_gunicorn_py3_2
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_3
    display: Test_gunicorn_py3_3
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_4
    display: Test_gunicorn_py3_4
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_5
    display: Test_gunicorn_py3_5
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_6
    display: Test_gunicorn_py3_6
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_7
    display: Test_gunicorn_py3_7
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_8
    display: Test_gunicorn_py3_8
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_9
    display: Test_gunicorn_py3_9
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Test_gunicorn_py3_10
    display: Test_gunicorn_py3_10
    check: 'gunicorn'
    test: true
    run_py2_tests: false
    pip_cache_config:
      key: 'pip | $(Agent.OS) | datadog_checks_base/datadog_checks/base/data/agent_requirements.in'
      restoreKeys: |
        pip | $(Agent.OS)
      path: $(PIP_CACHE_DIR)