pr:
  branches:
    include:
    - master
  paths:
    include:
    - datadog_checks_base/datadog_checks/base/data/agent_requirements.in

trigger: none

jobs:
- job: 'compile_deps_linux_py27'
  displayName: 'Compile Deps - Linux - py27'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: linux
      python_version: "2.7"

- job: 'compile_deps_windows_py27'
  displayName: 'Compile Deps - Windows - py27'
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: windows
      python_version: "2.7"

- job: 'compile_deps_macos_py27'
  displayName: 'Compile Deps - MacOS - py27'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: darwin
      python_version: "2.7"

- job: 'compile_deps_linux_py38'
  displayName: 'Compile Deps - Linux - py38'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: linux
      python_version: "3.8"

- job: 'compile_deps_windows_py38'
  displayName: 'Compile Deps - Windows - py38'
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: windows
      python_version: "3.8"

- job: 'compile_deps_macos_py38'
  displayName: 'Compile Deps - MacOS - py38'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: darwin
      python_version: "3.8"

