pr:
  branches:
    include:
    - master
  paths:
    include:
    - datadog_checks_base/datadog_checks/base/data/agent_requirements.in

trigger: none

jobs:
- job: 'compile_deps_linux'
  displayName: 'Compile Deps - Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: linux
      python_version: "2.7"

- job: 'compile_deps_windows'
  displayName: 'Compile Deps - Windows'
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: windows
      python_version: "2.7"

- job: 'compile_deps_macos'
  displayName: 'Compile Deps - MacOS'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: darwin
      python_version: "2.7"

- job: 'compile_deps_linux'
  displayName: 'Compile Deps - Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: linux
      python_version: "3.8"

- job: 'compile_deps_windows'
  displayName: 'Compile Deps - Windows'
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: windows
      python_version: "3.8"

- job: 'compile_deps_macos'
  displayName: 'Compile Deps - MacOS'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: './templates/compile-deps.yml'
    parameters:
      sys_platform: darwin
      python_version: "3.8"

