# https://github.com/actions/labeler

name: PR Labels
on:
- pull_request

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/labeler@glob-all
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflows/config/labeler.yml

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - run: python .github/workflows/changelog-label-check.py
