name: release-hash-check

on:
  pull_request:
    branches:
      - master
    paths:
      - .in-toto/*.link

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run script
      run: |
        CHANGED_FILES=$(git diff --name-only master)
        python .github/workflows/release-hash-check.yml $CHANGED_FILES